# Generated by Django 2.1 on 2020-06-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0002_churchservices_event_giving_pastorsprofile_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchdetails',
            name='email_account',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='churchdetails',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='churchdetails',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='churchdetails',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='churchdetails',
            name='location',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='churchdetails',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
