# Generated by Django 2.1 on 2020-06-03 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0003_auto_20200602_1233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChurchDetails',
            new_name='AboutChurch',
        ),
    ]
