# Generated by Django 2.1 on 2020-06-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0005_auto_20200603_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutchurch',
            name='church_location',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
