# Generated by Django 2.1 on 2020-06-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0006_aboutchurch_church_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutchurch',
            name='church_branches',
        ),
        migrations.RemoveField(
            model_name='aboutchurch',
            name='church_location',
        ),
    ]
