# Generated by Django 2.1 on 2020-06-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0007_auto_20200603_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutchurch',
            name='website_link',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
