# Generated by Django 2.1 on 2020-06-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0009_contacts_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='email',
        ),
    ]
