# Generated by Django 2.1 on 2020-06-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0010_remove_contacts_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='number',
        ),
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
