# Generated by Django 2.1 on 2020-06-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swapp', '0011_auto_20200606_1701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
